name: Makefile CI

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt install libssh-dev

    - name: optimized
      run: make optimized

    - name: Upload Built Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: spaceGame-x86_64
        path: spaceGame
