name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python dependencies
      run: sudo apt install libssh-dev

    - name: optimized
      run: make optimized

    - name: Upload Built Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: spacegame
        path: x86_64
